//
function loadEnergyTypes() {
    let energy_info_id = localStorage.getItem('energy_id');
}

let energy_info_page = [
    {id: 1, title: "Solar Energy", description: "Solar energy is harnessed from the sun's rays and converted into electricity or heat.", image_url: "Images/solar.png", information_description: "Solar energy generation is the process of turning sunlight into electricity that we can use every day. The most common way to do this is with solar panels, which contain photovoltaic (PV) cells. When sunlight hits these cells, it releases tiny particles called electrons, creating an electric current that can power homes, schools, and businesses. Another method, called solar thermal energy, uses mirrors to concentrate sunlight and produce heat, which then creates steam to spin a turbine and generate electricity." +
        "One of the biggest advantages of solar energy is that it's renewable and clean. The sun provides a constant source of energy, and using it doesn't release pollution or greenhouse gases. Solar panels also have low maintenance costs once installed and can help lower electricity bills over time. In addition, solar energy can give people more energy independence, as they can generate their own power instead of relying only on large energy companies." +
        "However, there are also some disadvantages. Solar panels only work when there is sunlight, so cloudy weather and nighttime can reduce electricity production. To keep power available all the time, batteries are often needed to store extra energy, which can be expensive. The initial cost of installing solar panels is also quite high, and large systems need plenty of space on rooftops or land. While solar energy is much better for the planet than fossil fuels, making the panels still requires materials and energy, which can have some environmental impact." +
        "Overall, solar energy is a clean, renewable, and increasingly popular way to produce electricity. Though it has some limits, its benefits for the environment and its potential to create a sustainable future make it one of the most promising energy sources available today."},

    {id: 2, title: "Wind Energy", description: "Wind energy is generated by converting wind currents into electricity using wind turbines.", image_url: "Images/wind energy.png", information_description: "Wind energy generation is the process of using the power of moving air to make electricity. This is done with wind turbines, which have large blades that spin when the wind blows. The spinning blades turn a shaft connected to a generator, which then produces electricity. Wind turbines are often built in groups called wind farms, either on land or out at sea, where winds are stronger and more consistent." +
        "One of the main advantages of wind energy is that it's renewable and clean. Wind will never run out, and using it doesn't produce air pollution or greenhouse gases. It's also a great way to reduce dependence on fossil fuels and fight climate change. Once turbines are installed, they have low operating costs and can provide steady energy in windy areas. Wind farms can also be built on farmland, allowing farmers to earn extra income while still using their land for crops or animals." +
        "However, wind energy also has some disadvantages. It depends on the weather, so electricity production can drop when the wind is weak or too strong. Some people find turbines noisy or unattractive, and they can affect local wildlife, especially birds and bats. Wind farms require large open areas, which can make it difficult to build them near cities where power is needed most. The initial cost of building turbines and connecting them to the power grid can also be high, though it's cheaper in the long term." +
        "Overall, wind energy is a sustainable, eco-friendly, and growing source of power. While it isn't perfect and works best in windy locations, its benefits for the environment and its ability to produce clean electricity make it a key part of a greener future"},

    {id: 3, title: "Hydropower", description: "Hydropower utilizes the energy of flowing water to produce electricity through dams or water turbines.", image_url: "Images/hydropower.png", information_description: "Hydropower energy generation uses the movement of water to make electricity. Most hydropower plants are built on rivers or dams, where flowing or falling water turns large turbines connected to generators. As the water moves through, it spins the turbines, producing clean and steady electricity." +
        "The biggest advantages of hydropower are that it's renewable, reliable, and produces no air pollution. It can generate a lot of energy and can be easily adjusted to meet electricity needs, making it great for providing steady power. Hydropower plants can also store water in dams, allowing energy to be produced when demand is high." +
        "However, hydropower also has disadvantages. Building dams can flood large areas, damaging wildlife habitats and sometimes forcing people to move. It can also change river ecosystems, affecting fish and water quality. Hydropower plants are also expensive to build, though they last a long time once complete." +
        "Overall, hydropower is a clean and dependable energy source, but it must be carefully managed to reduce its environmental impact."},

    {id: 4, title: "Geothermal Energy", description: "Geothermal energy is derived from the Earth's internal heat and can be used for heating and electricity generation.", image_url: "Images/geothermal energy.png", information_description: "Geothermal energy generation uses heat from beneath the Earth's surface to make electricity. Hot water or steam from underground is brought up through wells and used to spin a turbine connected to a generator. Some geothermal systems also use the Earth's heat directly for warming buildings." +
        "The main advantages of geothermal energy are that it's renewable, reliable, and always available, since the Earth's heat doesn't depend on weather. It produces very little pollution and takes up much less space than wind or solar farms." +
        "The disadvantages include the high cost of drilling deep into the ground and the fact that geothermal plants can only be built in places where hot rock is close to the surface. In rare cases, drilling can release underground gases or cause minor earthquakes." +
        "Overall, geothermal energy is a clean and consistent source of power, especially in volcanic or tectonic regions."},

    {id: 5, title: "nuclear Energy", description: "Nuclear energy is produced through nuclear reactions, typically using uranium or plutonium as fuel.", image_url: "Images/nuclear energy.png", information_description: "Nuclear energy generation comes from splitting atoms inside a reactor — a process called nuclear fission. When atoms (usually uranium) are split, they release a huge amount of heat, which is used to boil water, create steam, and spin turbines to generate electricity." +
        "The biggest advantages of nuclear energy are that it can produce large amounts of power without releasing greenhouse gases. It's very efficient, using small amounts of fuel to create a lot of energy, and it can provide a steady, reliable supply of electricity day and night." +
        "However, there are serious disadvantages. Nuclear power plants are very expensive to build, and radioactive waste must be safely stored for thousands of years. There's also the risk of accidents, which can cause long-lasting environmental damage, though such events are rare." + 
        "Overall, nuclear energy is a powerful and low-carbon source of electricity, but it comes with safety and waste challenges that must be carefully managed."},

    {id: 6, title: "Oil Energy", description: "Oil energy is obtained from crude oil and is used for transportation, heating, and electricity generation.", image_url: "Images/oil energy.png", information_description: "Oil energy generation involves burning oil or petroleum to heat water, creating steam that spins turbines to produce electricity. It's one of the oldest and most widely used forms of energy, especially for transportation and industrial use." +
        "The main advantages of oil are that it's energy-dense (a small amount produces a lot of power) and easy to transport and store. Oil power plants can also quickly adjust output to meet changing electricity needs." +
        "However, oil has many disadvantages. It's a non-renewable resource that will eventually run out, and burning it releases greenhouse gases and air pollution that contribute to climate change. Oil extraction and spills can also damage the environment." +
        "Overall, oil is a powerful but polluting energy source that's being replaced by cleaner, renewable alternatives."},

    {id: 7, title: "Coal Energy", description: "Coal energy is generated by burning coal to produce steam, which drives turbines to generate electricity.", image_url: "Images/coal energy.png", information_description: "Coal energy generation works by burning coal to heat water, creating steam that drives turbines to make electricity. It has been one of the world's main energy sources for over a century." +
        "The biggest advantages of coal are that it's abundant and cheap to use in many parts of the world. Coal plants can provide steady and reliable electricity at large scales." +
        "However, coal has serious disadvantages. Burning coal produces large amounts of carbon dioxide, sulfur, and other pollutants that harm the environment and human health. It's also a non-renewable resource, and mining coal can destroy landscapes and pollute waterways." +
        "Overall, while coal has been vital for powering industries and cities, it's one of the dirtiest energy sources, and many countries are moving away from it."},

    {id: 8, title: "Gas Energy", description: "Gas energy is produced by burning natural gas, which is a cleaner alternative to coal and oil for electricity generation.", image_url: "Images/gas energy.png", information_description: "Natural gas energy generation uses burning gas (mainly methane) to create heat, which then produces steam to turn turbines. It's commonly used in homes and power plants because it burns more cleanly than coal or oil." +
        "The advantages of natural gas include being more efficient and less polluting than other fossil fuels. It can also be used as a “bridge fuel”, helping countries move away from coal while developing renewable energy systems. Gas plants can start and stop quickly, making them useful for balancing electricity supply." +
        "However, natural gas is still a fossil fuel, meaning it produces carbon dioxide when burned. Leaks of methane, a powerful greenhouse gas, can also harm the environment. Extracting gas through methods like fracking can damage land and water supplies." +
        "Overall, natural gas is a cleaner fossil fuel option but not fully sustainable in the long term."},

    {id: 9, title: "Biomass Energy", description: "Biomass energy is derived from organic materials such as plant and animal waste, which can be converted into biofuels or used for heating.", image_url: "Images/biomass energy.png", information_description: "Biomass energy generation comes from burning organic materials such as wood, crop waste, or even animal manure to produce heat and electricity. It can also be converted into biofuels like ethanol and biodiesel for transport." +
        "The main advantages of biomass are that it's renewable and can reduce waste, since it uses materials that might otherwise be thrown away. It also helps reduce dependence on fossil fuels and can provide energy in rural areas." +
        "The disadvantages are that burning biomass still releases carbon dioxide, and if trees or crops are overused, it can harm the environment and reduce food supplies. Collecting and transporting biomass can also be costly and less efficient than other renewable sources.:" +
        "Overall, biomass is a renewable and versatile energy source, but it must be used carefully to remain sustainable and environmentally friendly."}
];

let speechUtterance = null;
let isPaused = false;

function speakText(text) {
    // Cancel any existing speech
    stopSpeaking();
    
    // Create new utterance
    speechUtterance = new SpeechSynthesisUtterance(text);
    speechUtterance.lang = 'en-US';
    speechUtterance.rate = 0.9;
    speechUtterance.pitch = 1;
    
    // Start speaking
    speechSynthesis.speak(speechUtterance);
    isPaused = false;
}

function pauseSpeaking() {
    if (speechSynthesis && !isPaused) {
        speechSynthesis.pause();
        isPaused = true;
    }
}

function resumeSpeaking() {
    if (speechSynthesis && isPaused) {
        speechSynthesis.resume();
        isPaused = false;
    }
}

function stopSpeaking() {
    if (speechSynthesis) {
        speechSynthesis.cancel();
        isPaused = false;
    }
}

//display the information based on what was clicked on the previous page
function display_energy_page(energy_info_page) {
    let energy_info_id = localStorage.getItem('energy_id');
    //alert('energy id: ' + energy_info_id);
    const container = document.getElementById('energy-info-container');
    const energy = energy_info_page.find(e => e.id == energy_info_id);
    if (energy) {
        const energyDiv = document.createElement('div');
        energyDiv.className = 'types-of-energy-information';
        energyDiv.innerHTML = `
            <h2>${energy.title}</h2>
            <img src="${energy.image_url}" alt="${energy.title}">
            <p>${energy.information_description}</p>
            <div class="speech-controls">
                <button onclick="speakText(this.parentElement.previousElementSibling.textContent)">
                    &#128265; Start Reading
                </button>
                <button onclick="pauseSpeaking()">
                    ⏸️ Pause
                </button>
                <button onclick="resumeSpeaking()">
                    ▶️ Resume
                </button>
                <button onclick="stopSpeaking()">
                    ⏹️ Stop
                </button>
            </div>
        `;
        container.appendChild(energyDiv);
    }
}
window.onload = display_energy_page(energy_info_page);

